#
# Makefile for nfc devices
#

obj-$(CONFIG_MICROREAD)		+= microread.o

microread-objs := open_nfc_main.o
microread-objs += open_nfc_custom.o
microread-objs += ccclient.o
microread-objs += ccclient_md.o
